import { BillingInterval, PlanType } from 'src/common';

export const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    name: 'Standard Monthly',
    description: 'Standard plan with monthly billing',
    planType: PlanType.STANDARD,
    billingInterval: BillingInterval.MONTHLY,
    price: 29.99,
    currency: 'USD',
    maxUsers: 5,
    maxJobs: 50,
    maxRTRs: 100,
    features: [
      { name: 'Basic job posting', isEnabled: true },
      { name: 'Standard support', isEnabled: true },
      { name: '5 team members', isEnabled: true },
      { name: '50 job postings', isEnabled: true },
      { name: '100 RTRs', isEnabled: true },
    ],
  },
  {
    name: 'Standard Yearly',
    description: 'Standard plan with yearly billing (2 months free)',
    planType: PlanType.STANDARD,
    billingInterval: BillingInterval.YEARLY,
    price: 299.99,
    currency: 'USD',
    maxUsers: 5,
    maxJobs: 50,
    maxRTRs: 100,
    features: [
      { name: 'Basic job posting', isEnabled: true },
      { name: 'Standard support', isEnabled: true },
      { name: '5 team members', isEnabled: true },
      { name: '50 job postings', isEnabled: true },
      { name: '100 RTRs', isEnabled: true },
      { name: '2 months free', isEnabled: true },
    ],
  },
  {
    name: 'Premium Monthly',
    description: 'Premium plan with monthly billing',
    planType: PlanType.PREMIUM,
    billingInterval: BillingInterval.MONTHLY,
    price: 99.99,
    currency: 'USD',
    maxUsers: 25,
    maxJobs: 200,
    maxRTRs: 500,
    features: [
      { name: 'Advanced job posting', isEnabled: true },
      { name: 'Priority support', isEnabled: true },
      { name: '25 team members', isEnabled: true },
      { name: '200 job postings', isEnabled: true },
      { name: '500 RTRs', isEnabled: true },
      { name: 'Advanced analytics', isEnabled: true },
      { name: 'Custom branding', isEnabled: true },
    ],
  },
  {
    name: 'Premium Yearly',
    description: 'Premium plan with yearly billing (2 months free)',
    planType: PlanType.PREMIUM,
    billingInterval: BillingInterval.YEARLY,
    price: 999.99,
    currency: 'USD',
    maxUsers: 25,
    maxJobs: 200,
    maxRTRs: 500,
    features: [
      { name: 'Advanced job posting', isEnabled: true },
      { name: 'Priority support', isEnabled: true },
      { name: '25 team members', isEnabled: true },
      { name: '200 job postings', isEnabled: true },
      { name: '500 RTRs', isEnabled: true },
      { name: 'Advanced analytics', isEnabled: true },
      { name: 'Custom branding', isEnabled: true },
      { name: '2 months free', isEnabled: true },
    ],
  },
];
