import { PlanType, BillingInterval } from '../../subscriptions/entities/subscription-plan.entity';

export const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    name: 'Standard Monthly',
    description: 'Standard plan with monthly billing',
    planType: PlanType.STANDARD,
    billingInterval: BillingInterval.MONTHLY,
    price: 29.99,
    currency: 'USD',
    maxUsers: 5,
    maxJobs: 50,
    maxRTRs: 100,
    features: ['Basic job posting', 'Standard support', '5 team members', '50 job postings', '100 RTRs'],
  },
  {
    name: 'Standard Yearly',
    description: 'Standard plan with yearly billing (2 months free)',
    planType: PlanType.STANDARD,
    billingInterval: BillingInterval.YEARLY,
    price: 299.99,
    currency: 'USD',
    maxUsers: 5,
    maxJobs: 50,
    maxRTRs: 100,
    features: ['Basic job posting', 'Standard support', '5 team members', '50 job postings', '100 RTRs', '2 months free'],
  },
  {
    name: 'Premium Monthly',
    description: 'Premium plan with monthly billing',
    planType: PlanType.PREMIUM,
    billingInterval: BillingInterval.MONTHLY,
    price: 99.99,
    currency: 'USD',
    maxUsers: 25,
    maxJobs: 200,
    maxRTRs: 500,
    features: ['Advanced job posting', 'Priority support', '25 team members', '200 job postings', '500 RTRs', 'Advanced analytics', 'Custom branding'],
  },
  {
    name: 'Premium Yearly',
    description: 'Premium plan with yearly billing (2 months free)',
    planType: PlanType.PREMIUM,
    billingInterval: BillingInterval.YEARLY,
    price: 999.99,
    currency: 'USD',
    maxUsers: 25,
    maxJobs: 200,
    maxRTRs: 500,
    features: [
      'Advanced job posting',
      'Priority support',
      '25 team members',
      '200 job postings',
      '500 RTRs',
      'Advanced analytics',
      'Custom branding',
      '2 months free',
    ],
  },
];
